version: '3.1'

services:
  app:
    build: .
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=sneakersinventory
      - DB_USER=root
      - DB_PASSWORD=root

  db:
    image: postgres
    environment:
      POSTGRES_DB: sneakersinventory
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"
